
import { Product, Translation } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'wollo-01',
    name: 'Wollo Kemis - Traditional Chic',
    nameAm: 'የወሎ ባህል ቀሚስ',
    description: 'Authentic Wollo embroidery featuring the iconic colorful Tilet patterns on premium hand-spun cotton.',
    descriptionAm: 'በጥጥ የተሰራ የወሎ ባህል ቀሚስ በደማቅ ጥበብ የተሸለመ።',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1000&auto=format&fit=crop',
    category: 'Women',
    sizes: ['S', 'M', 'L'],
    colors: ['White', 'Cream'],
    isFeatured: true
  },
  {
    id: 'gondar-01',
    name: 'Gondar Royal Kemis',
    nameAm: 'የጎንደር ባህል ቀሚስ',
    description: 'Inspired by the royalty of Gondar, this dress features thick, elegant embroidery patterns.',
    descriptionAm: 'የጎንደር ነገስታት የሚለብሱት አይነት ጥበብ ያለው ቀሚስ።',
    price: 12000,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop',
    category: 'Women',
    sizes: ['M', 'L', 'XL'],
    colors: ['White'],
    isFeatured: true
  },
  {
    id: 'tigray-01',
    name: 'Tigray Habesha Libs',
    nameAm: 'የትግራይ ባህል ልብስ',
    description: 'Exquisite Tilfi embroidery from the Tigray region, hand-stitched on lightweight cotton.',
    descriptionAm: 'የትግራይ ባህል ልብስ (ትልፊ) በእጅ የተሰፋ።',
    price: 15500,
    image: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?q=80&w=1000&auto=format&fit=crop',
    category: 'Women',
    sizes: ['S', 'M'],
    colors: ['White', 'Gold'],
    isFeatured: true
  }
];

export const TRANSLATIONS: Record<'en' | 'am', Translation> = {
  en: {
    navHome: 'Home',
    navShop: 'Collection',
    navAdmin: 'Admin',
    navOrders: 'My Orders',
    navLogin: 'Login',
    navLogout: 'Logout',
    navProfile: 'Profile',
    heroTitle: 'Authentic Habesha Tradition',
    heroSub: 'Hand-woven Ethiopian excellence delivered to your doorstep.',
    featuredTitle: 'Masterpiece Collection',
    buyNow: 'Order Now',
    viewDetails: 'Detail',
    orderTitle: 'Complete Your Order',
    fullName: 'Full Name (First Father)',
    phoneNumber: 'Phone Number (+251...)',
    deliveryAddress: 'Shipping Address',
    submitOrder: 'Confirm Order',
    successOrder: 'Order Received! Track it in "My Orders".',
    footerContact: 'Customer Support',
    size: 'Size',
    color: 'Color',
    category: 'Category',
    searchPlaceholder: 'Search collections...',
    all: 'All Heritage',
    price: 'Price',
    statusPending: 'Pending',
    statusApproved: 'Approved',
    statusDeclined: 'Declined',
    loginTitle: 'Sign In',
    signupTitle: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    fullNameError: 'Full name must include space (First Father)',
    passwordError: 'Password must be at least 6 digits',
    authError: 'Invalid email or password',
    duplicateError: 'Email or phone already registered',
    loginRequired: 'Please login or signup to continue',
    show: 'Show',
    hide: 'Hide',
    productDetails: 'Product Heritage Details'
  },
  am: {
    navHome: 'መነሻ',
    navShop: 'ምርቶች',
    navAdmin: 'አስተዳዳሪ',
    navOrders: 'ትዕዛዞቼ',
    navLogin: 'ግባ',
    navLogout: 'ውጣ',
    navProfile: 'ፕሮፋይል',
    heroTitle: 'እውነተኛ የሀበሻ ጥበብ',
    heroSub: 'በእጅ የተሰሩ ምርጥ የኢትዮጵያ ባህል ልብሶች።',
    featuredTitle: 'ልዩ ምርቶቻችን',
    buyNow: 'አሁኑኑ ይዘዙ',
    viewDetails: 'ዝርዝር',
    orderTitle: 'ትእዛዝዎን ያጠናቅቁ',
    fullName: 'ሙሉ ስም (የራስ የአባት)',
    phoneNumber: 'የስልክ ቁጥር (+251...)',
    deliveryAddress: 'የማድረሻ አድራሻ',
    submitOrder: 'ትእዛዝ አረጋግጥ',
    successOrder: 'ትእዛዝዎ ደርሶናል! "ትዕዛዞቼ" ውስጥ መከታተል ይችላሉ።',
    footerContact: 'ያግኙን',
    size: 'መጠን',
    color: 'ቀለም',
    category: 'ምድብ',
    searchPlaceholder: 'ምርቶችን ይፈልጉ...',
    all: 'ሁሉም',
    price: 'ዋጋ',
    statusPending: 'በሂደት ላይ',
    statusApproved: 'ጸድቋል',
    statusDeclined: 'ተሰርዟል',
    loginTitle: 'ይግቡ',
    signupTitle: 'ይመዝገቡ',
    email: 'ኢሜይል',
    password: 'የይለፍ ቃል',
    dontHaveAccount: "አካውንት የለዎትም?",
    alreadyHaveAccount: 'አካውንት አለዎት?',
    fullNameError: 'ሙሉ ስም የራስ እና የአባት ስም መያዝ አለበት',
    passwordError: 'የይለፍ ቃል ቢያንስ 6 አሃዝ መሆን አለበት',
    authError: 'የተሳሳተ ኢሜይል ወይም የይለፍ ቃል',
    duplicateError: 'ኢሜይል ወይም ስልክ አስቀድሞ ተመዝግቧል',
    loginRequired: 'እባክዎ ለመቀጠል ይግቡ ወይም ይመዝገቡ',
    show: 'አሳይ',
    hide: 'ደብቅ',
    productDetails: 'የምርት ዝርዝር መረጃ'
  }
};
